ALTER TABLE AREAS_INTERESSE ADD CONSTRAINT FK_AREAS_INTERESSE_PROFESSOR_PROFESSORES FOREIGN KEY(FK_PROFESSOR_UID) REFERENCES PROFESSORES;
ALTER TABLE AVALIACOES ADD
    (
    CONSTRAINT FK_AVALIACOES_ALUNO_ALUNOS FOREIGN KEY(FK_ALUNO_UID) REFERENCES ALUNOS,
    CONSTRAINT FK_AVALIACOES_PROFESSOR_PROFESSORES FOREIGN KEY(FK_PROFESSOR_UID) REFERENCES PROFESSORES
    );
ALTER TABLE BANCAS ADD
    (
    CONSTRAINT FK_BANCAS_ALUNO_ALUNOS FOREIGN KEY(FK_ALUNO_UID) REFERENCES ALUNOS,
    CONSTRAINT FK_BANCAS_ORIENTADOR_PROFESSORES FOREIGN KEY(FK_ORIENTADOR_UID) REFERENCES PROFESSORES,
    CONSTRAINT FK_BANCAS_PROPOSTA_PROPOSTAS FOREIGN KEY(FK_PROPOSTA_UID) REFERENCES PROPOSTAS
    );
ALTER TABLE BANCAS_AVALIADORES ADD
    (
    CONSTRAINT FK_BANCAS_AVALIADORES_BANCA_BANCAS FOREIGN KEY(FK_BANCA_UID) REFERENCES BANCAS,
    CONSTRAINT FK_BANCAS_AVALIADORES_PROFESSOR_PROFESSORES FOREIGN KEY(FK_AVALIADOR_UID) REFERENCES PROFESSORES
    );
ALTER TABLE PROFESSORES ADD CONSTRAINT FK_PROFESSORES_TITULO_TITULOS FOREIGN KEY(FK_TITULO_UID) REFERENCES TITULOS;
ALTER TABLE PROPOSTAS ADD
    (
    CONSTRAINT FK_PROPOSTAS_AUTOR_ALUNOS FOREIGN KEY(FK_AUTOR_UID) REFERENCES ALUNOS,
    CONSTRAINT FK_PROPOSTAS_ORIENTADOR_PROFESSORES FOREIGN KEY(FK_ORIENTADOR_UID) REFERENCES PROFESSORES
    );
ALTER TABLE SUGESTOES ADD CONSTRAINT FK_SUGESTOES_PROFESSOR_PROFESSORES FOREIGN KEY(FK_PROFESSOR_UID) REFERENCES PROFESSORES;
